"""Index the sample repository (+ its git history) and record every demo query's real output.

    python scripts/run_demo_queries.py                       # default config (configs/full.yaml)
    python scripts/run_demo_queries.py --config configs/test_tiny.yaml

Writes artifacts/demo/demo_results.json (full explain responses) and demo_transcript.md
(top-3 per query with provenance), which docs/demo.md refers to.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from codefusion.config import load_config  # noqa: E402
from codefusion.retrieval.pipeline import CodeFusionEngine  # noqa: E402
from codefusion.versions.demo_history import make_demo_history  # noqa: E402
from codefusion.versions.incremental import index_path  # noqa: E402


def _line(r: dict) -> str:
    p = r["provenance"]
    ranks = ", ".join(f"{k.replace('_rank', '')}#{v}" for k, v in p.items() if k.endswith("_rank") and k not in ("fused_rank", "final_rank") and v)
    ev = "; ".join((r["structural_evidence"] + r["graph_evidence"])[:4])
    s = r["snippet"]
    return f"{r['rank']}. `{s['file']}:{s['lines'][0]}-{s['lines'][1]}` **{s['symbol']}** ({s['type']}) - {ranks}" + (f" - _{ev}_" if ev else "")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default="configs/full.yaml")
    ap.add_argument("--out", default="artifacts/demo")
    ap.add_argument("--top-k", type=int, default=5)
    args = ap.parse_args()
    out = ROOT / args.out
    out.mkdir(parents=True, exist_ok=True)
    cfg = load_config(ROOT / args.config)

    current = CodeFusionEngine(cfg)
    index_path(current, ROOT / "examples" / "sample_repo", "sample_repo")
    current.save(out / "index_current")
    history_repo = ROOT / "artifacts" / "demo_history_repo"
    make_demo_history(history_repo)
    history = CodeFusionEngine(cfg, embedder=current.embedder)
    index_path(history, history_repo, "demo_history_repo", history=True)
    history.save(out / "index_history")

    queries = json.loads((ROOT / "examples" / "demo_queries.json").read_text(encoding="utf-8"))
    results = []
    md = [f"# Demo transcript ({cfg.name}, model {cfg.dense.model})", "",
          "Generated by `scripts/run_demo_queries.py`; real engine output on `examples/sample_repo` "
          "(and its 3-commit history for EVOLUTION / version queries).", ""]
    for q in queries:
        eng = history if q.get("version") == "all" else current
        resp = eng.search(q["query"], top_k=args.top_k, version=q.get("version")).to_dict(explain=True)
        results.append({"query": q, "index": "history" if eng is history else "current", "response": resp})
        md.append(f"## {q['query']}")
        md.append(f"intent **{resp['intent']}** ({resp['intent_confidence']:.2f}), scope `{resp['version_scope']}`, "
                  f"{resp['timings_ms']['total']:.1f} ms, candidates {resp['candidate_counts']}")
        md.append("")
        md += [_line(r) for r in resp["results"][:3]]
        for r in resp["results"][:3]:
            if r.get("lineage"):
                chain = " -> ".join(f"{x['symbol']}@{(x['commit'] or '')[:7]}" for x in r["lineage"])
                md.append(f"   lineage of #{r['rank']}: {chain}")
        md.append("")
    (out / "demo_results.json").write_text(json.dumps(results, indent=2, default=str), encoding="utf-8")
    (out / "demo_transcript.md").write_text("\n".join(md), encoding="utf-8")
    print("\n".join(md))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
