"""Pick the P0 (AppsRetrieval) configuration from measured ablation results — no hand-picking.

Reads artifacts/ablations/ablations_full.json, takes the experiment with the best NDCG@10
(ties -> better MRR@10 -> lower P50 latency), and writes configs/p0_apps.yaml as
``extends: <base config>`` + that experiment's overrides. Components that did not improve the
score are therefore absent from the P0 config (the "every component must earn its place" rule).

    python scripts/select_p0_config.py
"""

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from codefusion.config import apply_overrides, load_config  # noqa: E402
from codefusion.evaluation.ablation import default_experiments  # noqa: E402


def _nest(overrides: list[str]) -> dict:
    return apply_overrides({}, overrides)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ablations", default="artifacts/ablations/ablations_full.json")
    ap.add_argument("--out", default="configs/p0_apps.yaml")
    args = ap.parse_args()
    data = json.loads((ROOT / args.ablations).read_text(encoding="utf-8"))
    rows = [r for r in data["rows"] if r.get("status") == "ok" and r.get("ndcg_at_10") is not None]
    if not rows:
        print("no successful ablation rows")
        return 1
    best = sorted(rows, key=lambda r: (-r["ndcg_at_10"], -(r["mrr_at_10"] or 0), r["p50_latency_ms"] or 0))[0]
    exp = {e.key: e for e in default_experiments()}[best["experiment"]]
    out = ROOT / args.out
    base = Path(os.path.relpath(ROOT / data["base_config"], out.parent)).as_posix()
    body = {"extends": base, "name": "p0_apps",
            "description": f"AppsRetrieval P0 config = ablation {best['experiment']} ({best['name']}): "
                           f"NDCG@10 {best['ndcg_at_10']:.4f}, MRR@10 {best['mrr_at_10']:.4f} ({data['dataset']} AppsRetrieval test split).",
            **_nest(exp.overrides)}
    ranking = "\n".join(f"#   {r['experiment']:>3} {r['name']:<40} NDCG@10 {r['ndcg_at_10']:.4f}  MRR@10 {r['mrr_at_10']:.4f}"
                        for r in sorted(rows, key=lambda r: -r["ndcg_at_10"]))
    header = ("# GENERATED by scripts/select_p0_config.py from " + args.ablations + " - do not hand-edit.\n"
              f"# Measured ablation ranking ({data['dataset']} AppsRetrieval test split):\n" + ranking + "\n")
    out.write_text(header + yaml.safe_dump(body, sort_keys=False), encoding="utf-8")
    load_config(out)  # validate
    print(out.read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
